name: "Nightly Build (master)"
on:
  push:
    branches:
      - dev

jobs:
  publish-nightly:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install frontend dependencies    
        run: yarn install

      - name: Build app
        run: yarn tauri build

      - name: Produce artifacts
        uses: actions/upload-artifact@v3
        with:
            name: "nucleus-v0.2-nightly.${{github.run_number}}"
            path: "dist/"
